# ----------------------------
# Configuration Kafka KRaft
# ----------------------------

# Dossier des logs Kafka
log.dirs=C:/Users/HP/Desktop/BigDataLogsProject/kafka/kraft-logs

# Identité du nœud
node.id=1
process.roles=broker,controller

# Listeners
listeners=PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
controller.listener.names=CONTROLLER
inter.broker.listener.name=PLAINTEXT

# Quorum des controllers
controller.quorum.voters=1@localhost:9093

# Options de performance
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600

# Rétention des logs
log.retention.hours=168
log.segment.bytes=1073741824
